
services:
  alpine-postfix-hl:
    image: hackinglab/alpine-postfix-hl:latest
    hostname: postfix
    build: .
    restart: always
    environment:
      TZ: Europe/Zurich
      # Uncomment to enable debugging messages:
      #LOGXI: '*'
      maildomain: hacking-lab.com
      smtp_user: ivan.buetler:EBp5CJNcykf7cgmb,no-reply:FIj8qVxZXINXjJOC
    ports:
      - "25:25"
      - "587:587"
      - "25587:587"
